FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD fraud.jar /opt/fraud/
EXPOSE 8080
WORKDIR /opt/fraud/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "fraud.jar"]
